version: '3.9'

services:
  redis:
    image: redis:7.0.4
    container_name: redis
    ports:
      - 6379:6379
    command: '--requirepass password'
    volumes:
      - redis:/data
  
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports: 
      - "27017:27017"
    volumes: 
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 18081:8081

volumes:
  redis:
